# Generated by Django 5.2.17 on 2026-09-11 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bi_links', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acessado_em', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acessos', to='bi_links.linkbi')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acessos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acessado_em'],
                'indexes': [models.Index(fields=['usuario', 'acessado_em'], name='auditoria_a_usuario_089373_idx')],
            },
        ),
    ]
