# Generated by Django 5.2.17 on 2026-09-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_links', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='links_liberados',
            field=models.ManyToManyField(blank=True, related_name='funcionarios_liberados', to='bi_links.linkbi'),
        ),
    ]
