# Generated by Django 5.2.17 on 2026-09-11 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_backfill_links_liberados'),
        ('setores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='setores.setor'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='setores',
            field=models.ManyToManyField(blank=True, related_name='funcionarios_antigo', to='setores.setor'),
        ),
    ]
