# Generated by Django 5.2.17 on 2026-09-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_backfill_setor_unico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='setores',
        ),
    ]
