# Generated by Django 5.2.17 on 2026-09-11 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setores', to='empresas.empresa')),
            ],
            options={
                'ordering': ['empresa__nome', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nome'), name='setor_unico_por_empresa')],
            },
        ),
    ]
