# Generated by Django 5.2.17 on 2026-09-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ADMIN_EMPRESA', 'Admin da Empresa'), ('DIRETOR', 'Diretor'), ('NORMAL', 'Usuário Normal')], default='NORMAL', max_length=13),
        ),
    ]
